include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.gr.dart'
    - '**/*.moor.dart'
    - 'build/**'

linter:
  rules:
    avoid_print: false  # Allow print for debugging